# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define() do

  create_table "Authors", :force => true do |t|
    t.column "vorname",     :text
    t.column "nachname",    :text
    t.column "geburtsjahr", :integer
    t.column "todesjahr",   :integer
  end

  create_table "Autoren", :force => true do |t|
    t.column "vorname",               :text
    t.column "nachname",              :text
    t.column "geburtsjahr",           :date
    t.column "todesjahr",             :date
    t.column "geburtsjahr_gesichert", :boolean
    t.column "todesjahr_gesichert",   :boolean
    t.column "geburtstag",            :date
    t.column "todestag",              :date
    t.column "geburtsort",            :text
    t.column "todesort",              :text
    t.column "created_at",            :datetime
    t.column "updated_at",            :datetime
  end

  create_table "Onlinetexte", :force => true do |t|
    t.column "titel",             :text
    t.column "buchtitel",         :text
    t.column "verlag",            :text
    t.column "isbn_issn",         :text
    t.column "jahr",              :integer
    t.column "sprache",           :text
    t.column "originalsprache",   :text
    t.column "beschreibungslink", :text
    t.column "format",            :text
    t.column "typ",               :text
    t.column "empfohlener_link",  :boolean
    t.column "beschreibung",      :text
    t.column "autor_id",          :integer
    t.column "created_at",        :datetime
    t.column "updated_at",        :datetime
  end

  create_table "Shortstories", :force => true do |t|
    t.column "author_id", :integer
    t.column "titel",     :text
    t.column "jahr",      :integer
    t.column "sprache",   :text
  end

end
